---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCiV0zLfIG+Goe2jl3CgPq0zTPU5+biiKtrUxKYaA9801a7oHASsyyF5ucSJ3mdetrCU8MDtRzU7GjRmkP2B/Gd72S04Laqm4IKCxNjMDT3RupowBnvfsnOiicYst+pTwN7aIpi7RjVA7dd1P6TigZWtg6C5TS1rSfOa6RTew8ez/YSydIqayDZbO9i3HoGOTy8MjUt0XOzNaRMh/tiycqRtdYmQGMbEGxy0+PsY5ktM1KgwbJFKSXModAzlA8NUrfoKXlNK3X5HOunOOSbIUUtRgM+Yzz9kncyhKR/fXlXp/SWGk5rY/56tR2vqfQwkMwPpq2s0ZBWtIWcrzfuIe6WZuNLr511t9BhzLICAGx08DI8bXzGBPp/wSPyPpE7amewseM4zXgLRiqDQpDAEdxbJDqBxAzKlcywvACugEB0jDmzrK6rx0ePJUQMQe4u+b2VnaAgIy2knwcl7invGBq35Tzu3gklBVE9kJJ3TSBfPXVRxok4aAVBMppT1z2qXHZ1ybBiGvSiHXwC6Korjv38z1vbgxINPXzTlhJSs7fV1ogniVzh/Ft+WcqpRLlgMtKswMppeqiVanJCtvGFo+xyZksVdh7oHrItpjqejRJg31pPTLj4iDyWJQESQF/eBNC/Extg+vZw47NWk/T9gwEzBTr2dMTPCSCir0FbqAEazfyCdnxaP1f+XEKJsdd7GLo9QtI8ulyIqRCJtQWGVPlFCVksD1mvVPKs/6bGenhBHfio+b6ixAPBuDid0Dj3joFvcRfxjAfGmYWGHR9e0Q7vsQ8fvBR6szslVIOeuMq2bimtEZ6aUbrxH7WHKWN1b6Y9Q1DYT1aQDH6hWox9gVV5XFkbD/6zCEf+OEMSP1fFbpHVehXPnkykPYOM67/DG9qZeflWEu87tSjYiFlaJk6thDFJegs9PGScvJfHGxmh7vYNydrBJBGH
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
