apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - namespace.yaml
  - configmap.yaml
  - cloudflared-credentials-sealedsecret.yaml
  - deployment.yaml
