apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-cert-tls
  issuerRef:
    name: step-ca-acme
    kind: ClusterIssuer
  dnsNames:
  - argocd.lab.paroparo.it
