apiVersion: traefik.io/v1alpha1   # da verificare: kubectl api-resources | grep tlsstore
kind: TLSStore
metadata:
  name: default
  namespace: kube-system
spec:
  defaultCertificate:
    secretName: wildcard-lab-paroparo-it-tls
