apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme
spec:
  acme:
    server: https://192.168.178.5:9000/acme/acme/directory
    email: casini.cosimo@gmail.com
    privateKeySecretRef:
      name: step-ca-acme-account-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ4ekNDQVcyZ0F3SUJBZ0lRYWsvbm9EVGdpQ2dLZmF0czhXUVlQREFLQmdncWhrak9QUVFEQWpCQ01Sc3cKR1FZRFZRUUtFeEpJYjNWemRHOXVJRWh2YldWc1lXSWdRMEV4SXpBaEJnTlZCQU1UR2todmRYTjBiMjRnU0c5dApaV3hoWWlCRFFTQlNiMjkwSUVOQk1CNFhEVEkyTURZeE1ERXlNREl3TTFvWERUTTJNRFl3TnpFeU1ESXdNMW93ClFqRWJNQmtHQTFVRUNoTVNTRzkxYzNSdmJpQkliMjFsYkdGaUlFTkJNU013SVFZRFZRUURFeHBJYjNWemRHOXUKSUVodmJXVnNZV0lnUTBFZ1VtOXZkQ0JEUVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkdSSApWVWxBUFU2OEFreWZEYzltb0RjOC9qdkJ4U2lzcFkyWjRha1dJZTJYUEhUcnB4dk9keEhrQVFLRXRYSWhOSUsvCnN0c084dnVZd1RWR2dmQkJ4dk9qUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUcKQVFIL0FnRUJNQjBHQTFVZERnUVdCQlJ5cTRxMHJlZDR5U1NxY1RlVDg5VTlyeDhmR0RBS0JnZ3Foa2pPUFFRRApBZ05JQURCRkFpQjVSdHRuVW1kcG45TE85N1M3cUFUQkE5NXJERGVYSmlXeldNTkY1N1Jad0FJaEFOYlNRMFZuCjBGVFBIcGQ2dkQyd0tMYWt2MkhFVjZPSTdyVStuajJLSlZlcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik
