all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  hosts:
    houston:
      ansible_host: 192.168.178.2
      ansible_user: root
    iss:
      ansible_host: 192.168.178.3
      ansible_user: ansible
    sentinel:
      ansible_host: 192.168.178.4
      ansible_user: root
