---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgByISnrK9syzMHzRxTGK8eQcW/bLk3XtRwPr8faTgKEHYuWp+b9TdvbYe1swOtzdxhmUlAdIy/tkffG4qtD9UA2C8u4K5DBIkI0qf2PH+uozhLojLUdOFuV/dpT55XWdxZgm2BwpUz4IWKhHIVlhUElPFaL292xkLHsH9BwAj3FoiAdxxsrt5UIbhby8p7zuPY45BZMHLjqEcDQV8WGI01CqfQKTJrmm1/jSUDws0m83Xs2DfyL3zyZ4coB0sZUM1Tp5bxtQwHAY6lbs4fkR0OQnccOSeC/YkRDC3Sr9pyP9qYl1iBUL4ve0fKPbVj2k8+pO64p/XyvbyDf1Wjvr/plnLYFRqFLucj6DKRAr9Gxd4yxGWMkBY/3Nu8r9fHZ60ouygxn0ZfOw/HozXbhsojNHg8v7olphQRka4UXEPDoUb/KVGDVb3lQWhMXzRg0PzyYLZTxDBwOSe0NPdylswnKqDnZPI6mFagMwy3E7BchBztfjIeLCHVjO6DLObrPOPDpLxjxzU6hddlyP9hDaS3Ggimim90yJTwVp/Y0BOGupQLGaABqkXiEreLFdp5+MZoZXByWrWh/hIpHWWZgtjDs8BrQPKtpAt42GJcDxlOw4spcIAqpp66vz6CcJqGJYFFe14Ko1UIAyXC33hZMtnrGF8JDPE1RFatKZvFWUl334pqyBe7cAFIhxP2afLYzJoBtaAp+n1fKZ8qpWSmCxnCCF5bwqaE4y2FETOEaZf5zMIHr1B+CDd51XBXVjDC6sA0pckGwiA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
