apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme
spec:
  acme:
    server: https://192.168.178.5:9000/acme/acme/directory
    email: casini.cosimo@gmail.com
    privateKeySecretRef:
      name: step-ca-acme-account-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ4akNDQVcyZ0F3SUJBZ0lRSnNtN093cGoxRGY4RFF2ZDMrWFBGakFLQmdncWhrak9QUVFEQWpCQ01Sc3cKR1FZRFZRUUtFeEpJYjNWemRHOXVJRWh2YldWc1lXSWdRMEV4SXpBaEJnTlZCQU1UR2todmRYTjBiMjRnU0c5dApaV3hoWWlCRFFTQlNiMjkwSUVOQk1CNFhEVEkyTURZeE1ERXpNalV3T1ZvWERUTTJNRFl3TnpFek1qVXdPVm93ClFqRWJNQmtHQTFVRUNoTVNTRzkxYzNSdmJpQkliMjFsYkdGaUlFTkJNU013SVFZRFZRUURFeHBJYjNWemRHOXUKSUVodmJXVnNZV0lnUTBFZ1VtOXZkQ0JEUVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQksrZwo1c3c0ZkNoa1R3aUJibHVRN2JiNDdadVVoUUg1T2lWSkhFcFYzVjlsWDZmdUVTRTQ1SDIyWDNDVjNaeWR4OEJBClhuVytqT01VMFVnRVZ1VloyM2VqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUcKQVFIL0FnRUJNQjBHQTFVZERnUVdCQlNhQ0xTUVhuNnkxVk0xc09NT2hwbzM5SlJFbURBS0JnZ3Foa2pPUFFRRApBZ05IQURCRUFpQVFvbDhRTXV2bFY0WDNEMmQxeTZiaU9FZDRlN1NlVm9zbml3SnlhM0tnYVFJZ1BoQm5kL2MvCjBQZVlKbWN2L3hLUFBkTXA4S1FnRXhpc3owWG80Nm9XWkI0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik
