---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    message: AgBS/F+D5AUT8EyhCL8p/1QaAQbKuQab+ASBAhHg6LE7MafxAkwP78QMJJniyv2P8xbEqAZjleK9YFO0ZL6bRRqrJHvS1r+rqo/lpkbVwblDi08McwHRpHgUCszO5ke/pcKQ6qHg1PJn6wKveHq26V0Ap9RqPt3zJq/lN3kxyXSWyZEnokgtXVS1Rjoiwy6KSX6mTNqsaiHqk9ZrDgNg9VeZE/LS7uoZ31w3Ykcb5/hf6N9WWTjs99nWfPjt4AxHOwSSjKHodp+iPuKu3yNCUsrA2HoEtLy2hthVWGM+RPd1TWyUYmeIQ4pRgogtO0aNCAcW00tNwWjkTcwcIVSIYF1MvRnIuL0C3fnDrZLDzw+qqbDsHGkVVbQqM/bVRqFz324c1tQCowVJvSoiixSyC/HGAsAFh+PslioKX4bNHhNTgRGDcTNUenyZvKh54kPT6syI3+TPxnlUV/iKkTqfSoDq+ts0DF5eCM9YfKprFVbY3Tmd9YlJVajnM5FF5aQ00/823huon0lpP9p2tsTzDNgxYVFOKd5GInG2dNaG2PzfRP1vm3PC3+ZTrQ8+3XyybKHp7kmAwnT/HgHBkel5mju2gq9Wlo2XYITMnvxpMKx/ExN03cGRmj88ZEjNKvdYn1lbtpuDS30Rj+WHMr0lkY7gENV7PDnNDj5VEssmpcbJAn/O/N4SwQyBvA8KeMSQ5UO6lC/ohR/aipnD5BumAQaO0lWsgjh1vzzG
  template:
    metadata:
      name: demo-secret
      namespace: default
